### ISSUE TITLE
OZ's contract-upgradeable not bundled

### ISSUE THREAD

**Issue by franfrandev** [unhackedctf/reaper#1]
Hey sir, nice work, I'm already looking forward the next time machine time leap !
Though, the OZ upgradeable contracts were not bundled by default. So I did:

```console
$ forge i OpenZeppelin/openzeppelin-contracts-upgradeable --no-commit
```

Then edited the remappings to fit:

```
ds-test/=lib/forge-std/lib/ds-test/src/
forge-std/=lib/forge-std/src/
@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts
@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts
```

and seems to work !

good day

**Comment by zobront** [comment]
Thank you! They aren't needed for the `ReaperVaultV2.sol` contract, but should have included for completeness.
